emberlight/api/urls.py
from django.urls import path

from . import views

app_name = "api"


urlpatterns = [
    path("stripe/", views.stripe_webhook_handler),
    path("github/", views.github_webhook_handler),
]

emberlight/emberlight/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include
from django.urls import path

urlpatterns = [
    path("", include("main.urls")),
    path("admin/", admin.site.urls),
    path("write/", include("write.urls")),
    path("account/", include("account.urls")),
    path("chat/", include("chat.urls")),
    path("updates/", include("updates.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("api/", include("api.urls")),
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path(
        "password-change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="registration/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password-change/",
        auth_views.PasswordChangeView.as_view(template_name="registration/password_change.html"),
        name="password_change",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirmed.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html"),
        name="password_reset",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emberlight/main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.home_page),
    path("robots.txt/", views.robots_txt),
    path("pricing/", views.pricing_page, name="pricing"),
    path("checkout/", views.checkout, name="checkout"),
    path("payment/", views.payment, name="payment"),
    path("payment/success", views.payment_success, name="payment_success"),
    path("contact/thanks/", views.contact_thanks),
    path("contact/", views.contact_page),
    path("support/", views.support_page),
    path("terms-of-service/", views.terms_of_service),
    path("privacy-policy/", views.privacy_policy),
    path("presskit/", views.presskit),
    path("ref/<str:coupon_id>/", views.referral_code),
    path("test/", views.test, name="test"),
]

emberlight/main/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(required=True)


class PricingForm(forms.Form):
    couponcode = forms.CharField(required=False)

emberlight/main/views.py
import ast
import datetime
import json
import time
import traceback

import dateutil.relativedelta
import redis
import stripe
from account.models import MiscUserInfo
from account.models import StripeCustomerData
from api.models import StripeCoupon
from decouple import config
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import BadHeaderError
from django.core.mail import send_mail
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.views.decorators.http import require_GET
from django.views.decorators.http import require_POST

from .forms import ContactForm
from .forms import PricingForm

# -- Database Settings -- #
rdb = redis.Redis(
    host="localhost", port=6379, db=0, password=config("REDIS_PASSWORD"), decode_responses=True
)


# Do most of the logic here before rendering
stripe.api_key = settings.STRIPE_SECRET_KEY


def home_page(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            from_email = form.cleaned_data.get("email")
            message = form.cleaned_data.get("message")
            message = from_email + "\n\n" + message
            try:
                send_mail(name, message, settings.EMAIL_HOST_USER, ["support@torchlightintel.com"])
            except BadHeaderError:
                return HttpResponse("Invalid header found.")
            return HttpResponseRedirect("/contact/thanks/")
        else:
            return HttpResponse("Make sure all fields are filled out and valid.")
    title = "Emberlight - Home"
    context = {"title": title}
    return render(request, "main/home.html", context)


def contact_page(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            from_email = form.cleaned_data.get("email")
            message = form.cleaned_data.get("message")
            message = from_email + "\n\n" + message
            print(name, from_email, message)
            try:
                send_mail(name, message, settings.EMAIL_HOST_USER, ["support@torchlightintel.com"])
            except BadHeaderError:
                return HttpResponse("Invalid header found.")
            return HttpResponseRedirect("/contact/thanks/")
        else:
            return HttpResponse("Make sure all fields are filled out and valid.")
    title = "Emberlight - Contact Us"
    return render(request, "main/contact.html", {"title": title})


@require_GET
def robots_txt(request):
    if settings.DEBUG:
        robots_txt_contents = ["User-Agent: *", "Disallow: /"]
    elif not settings.DEBUG:
        robots_txt_contents = ["User-Agent: *", "Disallow:"]
    return HttpResponse("\n".join(robots_txt_contents), content_type="text/plain")


def contact_thanks(request):
    title = "Emberlight - Thank You"
    return render(request, "main/contact-thanks.html", {"title": title})


def support_page(request):
    title = "Emberlight - Support"
    return render(request, "main/support.html", {"title": title})


def about_page(request):
    title = "Emberlight - About Us"
    return render(request, "main/about.html", {"title": title})


def payment_success(request):
    title = "Emberlight - Purchase Success!"
    return render(request, "main/payment-success.html", {"title": title})


def terms_of_service(request):
    return render(request, "main/terms-of-service.html")


def privacy_policy(request):
    return render(request, "main/privacy-policy.html")


def presskit(request):
    return render(request, "main/presskit.html")


def pricing_page(request):
    try:
        referral_code = request.GET["ref"]
    except Exception:
        referral_code = ""
    title = "Emberlight - Pricing"
    context = {"title": title, "referral_code": referral_code}
    if not request.user.is_authenticated:
        if referral_code == "":
            return redirect("/account/register/", context)
        else:
            return redirect("/account/register/?ref={}".format(referral_code), context)
    return render(request, "main/pricing.html", context)


def referral_code(request, coupon_id):
    referral_code = get_object_or_404(StripeCoupon, coupon_id=coupon_id)
    return redirect("/pricing/?ref={}".format(referral_code.coupon_id))


@login_required
def checkout(request):
    try:
        sub_name = request.GET["sub_name"]
    except Exception:
        return redirect("main/pricing.html")
        print("\n\nno sub_name query in URL\n\n")
    try:
        referral_code = request.GET["ref"]
    except Exception:
        referral_code = ""
    try:
        title = "Emberlight - Checkout"
        form = PricingForm(initial={"couponcode": referral_code})
        plan = settings.PLANS[
            sub_name
        ]  # variable "plan" is a dictionary with info about subscriptions.
        context = {
            "title": title,
            "STRIPE_PUBLISHABLE_KEY": settings.STRIPE_PUBLISHABLE_KEY,
            "form": form,
            "referral_code": referral_code,
            "sub_id": plan["stripe_id"],
            "price": plan["price"],
            "total_price": plan["total_price"],
            "payment_period": plan["payment_period"],
            "plan_name": plan["nickname"],
        }
        return render(request, "main/checkout.html", context)
    except KeyError:
        name = "THREAT: Invalid Payment Plan"
        message = "{}\n{}\n\n{}\n\n{}\n{}\n\nTraceback: {}".format(
            settings.EMAIL_HOST_USER,
            datetime.datetime.now(),
            "Someone tried to request a payment plan we don't support.",
            request.user,
            request.user.email,
            traceback.format_exc(),
        )
        send_mail(name, message, settings.EMAIL_HOST_USER, ["engineering@torchlightintel.com"])
        messages.error(request, "Invalid payment plan. This incident has been reported.")
        title = "Emberlight - Pricing"
        context = {"title": title, "key": settings.STRIPE_PUBLISHABLE_KEY}
        return redirect("/pricing", context)


@login_required
@require_POST
def payment(request):
    form = PricingForm(request.POST)
    # -- Data Validation -- #
    # Check to make sure the user is logged in
    if not request.user.is_authenticated:
        messages.error(request, "You must be logged in to subscribe.")
        title = "Emberlight - Pricing"
        context = {"title": title, "key": settings.STRIPE_PUBLISHABLE_KEY}
        return redirect(
            "/account/register/?next=/pricing/&ref={}".format(
                form.cleaned_data.get("couponcode") if form.is_valid() else ""
            ),
            context,
        )

    # Check to see if the user is already subscribed to a payment plan
    try:
        user_ID = StripeCustomerData.objects.all().get(username=request.user).customer_json
    except StripeCustomerData.DoesNotExist:
        user_ID = None
    try:
        subscription_ID = (
            StripeCustomerData.objects.all().get(username=request.user).subscription_json
        )
        if subscription_ID["status"] == "unpaid":
            messages.error(
                request,
                "There was an error the last time we tried to charge your card. Check your inbox for any emails from support@torchlightintel.com.",
            )
            title = "Emberlight - Home"
            context = {"title": title, "key": settings.STRIPE_PUBLISHABLE_KEY}
            return redirect("/", context)

    except StripeCustomerData.DoesNotExist:
        subscription_ID = None

    # user is created and subscribed
    # user is created and not subscribed
    # user is not created and subscribed (Can't happen!)
    # user is not created and not subscribed
    # Check for if the user has a subscription. If both checks fail, it is assumed that either the
    #   user exists but doesn't have an active subscription or the user doesn't exist and doesn't
    #   have a subscription.
    if user_ID and subscription_ID:
        if subscription_ID["status"] == "active":
            messages.error(request, "You already have a subscription.")
            title = "Emberlight - Home"
            context = {"title": title, "key": settings.STRIPE_PUBLISHABLE_KEY}
            return redirect("/", context)
    elif not user_ID and subscription_ID:
        print(
            "The user is not created and yet has a subscription. Something has gone terribly wrong."
        )

    # Handle coupons
    if form.is_valid():
        couponcode = form.cleaned_data.get("couponcode")
        stripe_coupon_code = ""
        trial_period_months = 1
        try:
            logged_in_user = MiscUserInfo.objects.all().get(username=request.user)
        except MiscUserInfo.DoesNotExist:
            if settings.DEBUG:
                MiscUserInfo(username=request.user.username, email=request.user.email).save()
                logged_in_user = MiscUserInfo.objects.all().get(username=request.user)
            elif not settings.DEBUG:
                messages.error(request, "There was an error processing your payment.")
                title = "Emberlight - Pricing"
                context = {"title": title, "key": settings.STRIPE_PUBLISHABLE_KEY}
                return redirect("/pricing", context)

        # Check for unique IndieGoGo and media specific codes
        with open("unique_coupon_codes.txt", "r+") as f:
            unique_coupon_codes = ast.literal_eval(f.read())
        if couponcode not in unique_coupon_codes:
            # messages.error(request, "Coupon code invalid.")
            try:
                stripe_coupon_code = StripeCoupon.objects.all().get(coupon_id=couponcode).coupon_id

emberlight/main/templates/main/checkout.html
<!doctype html>
{% extends "main/base.html" %}
{% block title %} {{ title }} {% endblock %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
<html lang="en">
<style type="text/css">
.StripeElement {
  box-sizing: border-box;

  height: 40px;

  padding: 10px 12px;

  border: 1px solid transparent;
  border-radius: 4px;
  background-color: white;

  box-shadow: 0 1px 3px 0 #e6ebf1;
  -webkit-transition: box-shadow 150ms ease;
  transition: box-shadow 150ms ease;
}

.StripeElement--focus {
  box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
  border-color: #fa755a;
}

.StripeElement--webkit-autofill {
  background-color: #fefde5 !important;
}
</style>
<script src="https://js.stripe.com/v3/"></script>
<!-- Checkout Info -->

<body class="login-page">
  <div class="page-header" style="position: relative; background-image: url({% static 'main/images/backgrounds/1280concert.jpg'%}), url({% static 'main/images/backgrounds/720concert.jpg'%}), url({% static 'main/images/backgrounds/480concert.jpg'%});">
    <div class="container-fluid">
      {# spacer #}
      <div class="row d-none d-md-block d-lg-none" style="height: 150px;"></div>
      {# end spacer #}
      <div class="row justify-content-center" style="margin-top: 100px;">
        {# Cart Deck #}
        <div class="col-md-6 col-lg-6 col-xl-3 align-self-center" style="padding: 0; margin: 15px;">
          <div class="container-fluid">
            <div class="row justify-content-center">
              <div class="card" style="margin: auto; margin-top: 0; padding: 0; min-height: 450px;">
                {# Desktop Cart Body #}
                <div class="card-body text-center d-none d-md-block" style="font-size: 24px;">
                  <div class="row justify-content-center" style="margin: 0; padding: 0;">
                  <i style="color: #3C4858; font-size: 86px; margin: 25px 25px 10px 14px;" class="fas fa-shopping-cart"></i>
                  </div>
                  {# <h3 class="card-title" style="margin: 0; font-size: 42px; font-weight: 600;">Cart</h3> #}
                  <div id="cart-body" style="min-height: 200px; margin: 25px 25px 0px 25px; text-align: left;">
                    <span class="cart-text"><i class="fas fa-notes-medical" style="font-size: 26px; margin-right: 22.5px;"></i>Plan: {{plan_name}}</span>
                    <br>
                    <span class="cart-text"><i class="fas fa-tag" style="margin-right: 18px;"></i>Subscription Price: ${{total_price}}</span>
                    <br>
                    <span class="cart-text"><i class="far fa-calendar-alt" style="margin-right: 22.5px;"></i>Payment Period: {{payment_period}}</span>
                    <br>
                    <span class="cart-text"><i class="material-icons" style="margin-right: 20px;">info</i>1 month free trial included *</span>
                  </div>
                  {# <div style="font-size: 72px; font-weight: 400; color: #3C4858; margin-top: 25px;"> #}
                    {# <i class="fas fa-shopping-cart"></i> #}
                  {# </div> #}
                  <div class="text-center" style="margin: 0px 0 10px 0;">
                    <span class="cart-text" style="font-size: 14px;">* payment begins only if subscription is allowed to auto-renew after free trial period has elapsed.</span>
                  </div>
                </div>
                {# End Desktop Cart Body #}
                {# Mobile Cart Body #}
                <div class="card-body text-center d-md-none" style="font-size: 24px;">
                  <div class="row justify-content-center" style="margin: 0; padding: 0;">
                  <i style="color: #3C4858; font-size: 86px; margin: 25px 25px 10px 14px;" class="fas fa-shopping-cart"></i>
                  </div>
                  {# <h3 class="card-title" style="margin: 0; font-size: 42px; font-weight: 600;">Cart</h3> #}
                  <div id="cart-body" style="min-height: 200px; margin: 25px 0px 0px 10px; text-align: left;">
                    <span class="cart-text" style="font-size: 20px;"><i class="fas fa-notes-medical" style="font-size: 30px; margin-right: 25px;"></i>Plan: </span><span class="cart-text" style="font-size: 20px; margin-left: 47px;">{{plan_name}}</span>
                    <br>
                    <span class="cart-text" style="font-size: 20px;"><i class="fas fa-tag" style="font-size: 26px; margin-right: 21px;"></i>Subscription Price: </span><span class="cart-text" style="font-size: 20px; margin-left: 46.5px;">${{total_price}}</span>
                    <br>
                    <span class="cart-text" style="font-size: 20px;"><i class="far fa-calendar-alt" style="font-size: 26px; margin-right: 25px;"></i>Payment Period: </span><span class="cart-text" style="font-size: 20px; margin-left: 47.5px;">{{payment_period}}</span>
                    <br>
                    <span class="cart-text" style="font-size: 20px;"><i class="material-icons" style="font-size: 30px; margin-right: 18px;">info</i>1 month free trial</span><span class="cart-text" style="font-size: 20px; margin-left: 49.5px;">included *</span>
                  </div>
                  {# <div style="font-size: 72px; font-weight: 400; color: #3C4858; margin-top: 25px;"> #}
                    {# <i class="fas fa-shopping-cart"></i> #}
                  {# </div> #}
                  <div class="text-center" style="margin: 15px 0 10px 0;">
                    <span class="cart-text" style="font-size: 14px;">* payment begins only if subscription is allowed to auto-renew after free trial period has elapsed.</span>
                  </div>
                </div>
                {# End Mobile Cart Body #}
              </div>
            </div>
          </div>
        </div>
        {# End Cart Deck #}
        {# spacer #}
        <div class="col-12 d-lg-none" style="height: 25px;"></div>
        {# end spacer #}
        {# Card Information #}
        <div class="col-md-12 col-lg-12 col-xl-3" style="padding: 0; margin: 0;">
          <div class="container-fluid">
            <div class="row">
              <div class="col-12 text-center" style="margin: 0; padding: 0;">
                <div class="row justify-content-center" style="margin: 0; padding: 0;">
                  <div class="col" style="min-width: 250px; max-width: 500px; height: auto;">
                    <div class="card" style="height: 450px;">
                      {# Large Header #}
                      <div class="card-header card-header-ember text-center shadowy-0 d-none d-lg-block">
                        <h3 class="card-title" style="margin-bottom: 10px;">Stop writing the hard way.</h3>
                      </div>
                      {# Small Header #}
                      <div class="card-header card-header-ember text-center shadowy-0 d-lg-none" style="padding: 15px;">
                        <h3 class="card-title" style="margin-bottom: 10px;">Stop writing the hard way.</h3>
                      </div>
                      <div class="card-body text-center" style="">
                        <form class="form" action="{% url 'main:payment' %}" method="post" id="payment-form">
                          <div class="container-fluid" style="margin: 0; padding: 0;">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            <input type="hidden" name="plan" value={{plan_name}}>
                            <h3 class="card-title pricing-card-title">Free Trial: $0</h3>
                            <div class="d-none d-lg-block">
                              <br>
                            </div>
                            <!-- Stripe - getting credit card token -->
                            <div class="">
                              <label for="card-element">
                                credit or debit card:
                              </label><br>
                              <div id="card-element">
                                <!-- A Stripe Element will be inserted here. -->
                              </div>
                              <!-- Used to display form errors. -->
                              <div id="card-errors" role="alert"></div>
                            </div>
                            <br>
                            <!-- Gathering other form data -->
                            <div class="input-group">
                              <div class="input-group-prepend">
                                <span class="input-group-text">
                                  <i class="material-icons">info</i>
                                </span>
                              </div>
                              {% render_field form.couponcode class="form-control" placeholder="Enter Coupon Code Here..." %}
                            </div>
                            <div class="row justify-content-center" style="margin: 0; padding: 0;">
                              {# Large Button #}
                              <button class="btn btn-raised btn-lg btn-ember shadowy-0 d-none d-lg-block" style="margin: 50px;">Submit Payment</button>
                              {# Small Button #}
                              <button class="btn btn-raised btn-lg btn-ember shadowy-0 d-lg-none" style="margin: 30px;">Make Purchase</button>
                            </div>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {# End Card Information #}
      </div>
    </div>
  </div>
  <div class="d-none d-lg-block">
    {% include "main/includes/footer.html" %}
  </div>
</body>
<script>
// set plan selection in payment form
document.getElementsByName('plan')[0].value = "{{plan_name}}";
</script>
<script type="text/javascript">
// Create a Stripe client.
var stripe = Stripe("{{ STRIPE_PUBLISHABLE_KEY }}");

// Create an instance of Elements.
var elements = stripe.elements();

// Custom styling can be passed to options when creating an Element.
// (Note that this demo uses a wider set of styles than the guide below.)
var style = {
  base: {
    color: '#32325d',
    fontFamily: '"Roboto", sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '16px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};

// Create an instance of the card Element.
var card = elements.create('card', { style: style });

// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');

// Handle real-time validation errors from the card Element.
card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});

// Handle form submission.
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the user if there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});

// Submit the form with the token ID.
function stripeTokenHandler(token) {
  // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}
</script>
{% endblock content %}

emberlight/main/templates/main/contact-thanks.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{title}} {% endblock %}
{% block content %}

<body class="login-page">
  <div class="page-header" style="position: relative; background-image: url({% static 'main/images/backgrounds/1280orangecity.jpg'%}), url({% static 'main/images/backgrounds/720orangecity.jpg'%}), url({% static 'main/images/backgrounds/480orangecity.jpg'%})">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-7 col-sm-9 ml-auto mr-auto">
          <div class="card card-login">
            <form class="form" method="POST">
              <div class="card-header card-header-ember text-center shadowy-0">
                <h3 class="card-title" style="margin-bottom: 10px;">Thank you.</h3>
              </div>
              {# <p class="description text-center">or be old school:</p> #}
              <div class="card-body" style="padding: 0;">
                <div class="message-card-text" style="font-size: 22px; margin: 50px 0 0 0;">
                  <font style="font-weight: 600;">
                    Your message has been received. <br><br>We'll get back to you as <br>soon as we can.</font>
                </div>
              </div>
              <div class="text-center" style="margin: 50px 0 0 0;">
                <p class="message-card-text">Click here to return to the homepage.</p>
                <a href="/" class="btn btn-ember btn-raised btn-lg shadowy-0" id="box-shadowy-0"><strong>Continue</strong></a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% include "main/includes/footer.html" %}
  </div>
</body>
{% endblock content %}

emberlight/main/templates/main/contact.html
{% extends "main/base.html" %}
{% load static %}
{% block title %} {{title}} {% endblock %}
{% block content %}

<body>
  <div class="backsplash" style="position: relative; background-image: url({% static 'main/images/backgrounds/offwhite.jpeg'%})">
    <div class="container-fluid">
      <div class="row" style="height: 12.5vh; background: linear-gradient(rgba(0,0,0,0.5), 20%, rgba(0,0,0,0.1), 75%, rgba(0,0,0,0));"></div>
      <div class="row justify-content-center">
        <div class="section section-contacts" style="height: 100%;">
          <div class="col-md-8 ml-auto mr-auto">
            <h2 class="text-center title">Questions? Comments? Cares? Concerns? Queries? Conundrums?</h2>
            <h4 class="text-center description">Email us about them</h4>
            <form class="contact-form" method="POST">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Your Name</label>
                    <input id="name" name="name" type="text" class="form-control">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Your Email</label>
                    <input id="email" name="email" type="email" class="form-control">
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label for="exampleMessage" class="bmd-label-floating">Your Message</label>
                <textarea id="message" name="message" type="text" class="form-control" rows="4"></textarea>
              </div>
              <div class="row">
                <div class="col-md-4 ml-auto mr-auto text-center">
                  <button type="submit" class="btn btn-ember btn-raised shadowy-0">
                    Send Message
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% include "main/includes/footer.html" %}
  </div>
</body>
{% endblock %}

emberlight/main/templates/main/payment-success.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{title}} {% endblock %}
{% block content %}

<body class="login-page">
  <div class="page-header" style="position: relative; background-image: url({% static 'main/images/backgrounds/1280orangecity.jpg'%}), url({% static 'main/images/backgrounds/720orangecity.jpg'%}), url({% static 'main/images/backgrounds/480orangecity.jpg'%})">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-7 col-sm-9 ml-auto mr-auto">
          <div class="card card-login">
            <form class="form" method="POST">
              <div class="card-header card-header-ember text-center shadowy-0">
                <h3 class="card-title" style="margin-bottom: 10px;">Checkout</h3>
              </div>
              {# <p class="description text-center">or be old school:</p> #}
              <div class="card-body" style="padding: 0;">
                <div class="message-card-text" style="font-size: 24px; margin: 50px 0 0 0;">
                  <font style="font-weight: 600;">
                    <h2>
                      <strong>
                        Purchase<br>Accepted
                      </strong>
                    </h2>
                  </font>
                </div>
              </div>
              <div class="text-center">
                <p class="message-card-text">Your free trial has begun!</p>
              </div>
              <div class="text-center" style="margin: 50px 0 0 0;">
                <p class="message-card-text">Click here to start writing!</p>
                <a href="/write/" class="btn btn-ember btn-raised btn-lg shadowy-0" id="box-shadowy-0"><strong>Continue</strong></a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% include "main/includes/footer.html" %}
  </div>
</body>
{% endblock content %}

emberlight/main/templates/main/post_update.html
{% extends "main/base.html" %}

{% block title %} {{title}} {% endblock %}

{% block content %}

<h1>{{ object.title }}</h1>
<p>{{ object.content }}</p>
<p>This page is for company updates</p>

{% endblock %}

emberlight/main/templates/main/subscription.html
{% extends "main/base.html" %}
{% load widget_tweaks %}
{% block title %} {{title}} {% endblock %}
{% block content %}
<h2>Thank you for paying for the {{plan}} plan!</h2>
{% endblock %}